# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-08 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0007_auto_20180507_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='source',
            field=models.CharField(default=b' ', max_length=300),
        ),
    ]
